/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.awt.Font;
import java.awt.font.TextAttribute;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.awt.print.PrinterException;
import java.lang.System.Logger.Level;
import java.text.AttributedString;
import java.util.logging.Logger;
import javax.print.PrintException;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.TimerTask;
import javax.swing.Timer;
import javax.swing.JOptionPane;
//import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author suvansharora
 */
public class hospital extends javax.swing.JFrame {
private JFrame frame;
    /**
     * Creates new form hospital
     */
    public hospital() {
        initComponents();
        //setter
        String url="jdbc:mysql://localhost:3306/hospital";
        String query="SELECT id,name,dob,address,govid,phno FROM prescription ORDER BY ID Desc Limit 1";
             String username1="root";
        String pass="";
        Connection conn=null;
        String a=null;
        String b=null;
        Statement s=null;
            try{
                Class.forName("com.mysql.jdbc.Driver");
        conn=DriverManager.getConnection(url,username1,pass);
        System.out.println("Connected");
        s=     (Statement) conn.createStatement();
        ResultSet rs=s.executeQuery(query);
        //System.out.println(rs);
        if(rs.next()){
                 int id=rs.getInt(1);
                 String id1=Integer.toString(id);
        String name=rs.getString(2);
        String dob=rs.getString(3);
        String address=rs.getString(4);
        String govid=rs.getString(5);
        String phno=rs.getString(6);
        jTextField13.setText(id1);
        jTextField16.setText(name);
        jTextField17.setText(dob);
        jTextField14.setText(govid);
        jTextField9.setText(address);
        jTextField15.setText(phno);
        }
        conn.close();
        
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);
            }
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       String url1="jdbc:mysql://localhost:3306/hospital";
        String query1="select id,name,disease,medicine,dosage,discripton from prescription;";
             String username="root";
        String pass1="";
        Connection con=null;
       // String a=null;
        //String b=null;
        Statement stt=null;
            try{
                Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection(url1,username,pass1);
        System.out.println("Connected bitch");
        stt=(Statement) con.createStatement();
        ResultSet rs=stt.executeQuery(query1);
        //System.out.println(rs);
        while(rs.next()){
                 int id=rs.getInt(1);
                 String id1=Integer.toString(id);
        String name=rs.getString(2);
        String disease=rs.getString(3);
        String medicine=rs.getString(4);
        String dosage=rs.getString(5);
        String discription=rs.getString(6);
        model.addRow(new Object[]{id1,name,disease,medicine,dosage,discription});
        }
        con.close();
        
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1450, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel1.setForeground(new java.awt.Color(51, 0, 51));

        jLabel2.setBackground(new java.awt.Color(51, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("PATEINT'S PRESCRIPTION");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(256, 256, 256))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 910, 70));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/proj.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/chomu.jpg"))); // NOI18N
        //jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/projo-page-001.jpg")));
        jLabel3.setText("jLabel1");
        jLabel3.setMaximumSize(new java.awt.Dimension(70, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(70, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(720, 685));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 32)); // NOI18N
        jLabel4.setText("AGARWAL MEDICAL CENTER");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel5.setText("EST. 1981");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel6.setText("PH.NO:01332-254456");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("HOSP. REG. NO.:UK/HR/AL/32/43");

        jLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/chomu.jpg"))); // NOI18N
        jLabel31.setText("jLabel1");
        jLabel31.setMaximumSize(new java.awt.Dimension(70, 50));
        jLabel31.setMinimumSize(new java.awt.Dimension(70, 50));
        jLabel31.setPreferredSize(new java.awt.Dimension(720, 685));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(741, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(jLabel4)
                                .addGap(83, 83, 83))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(182, 182, 182))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)))))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(794, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 120));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Krungthep", 1, 15)); // NOI18N
        jLabel8.setText("PATIENT'S PRESCRIPTION");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel9.setText("R");

        jLabel10.setText("x");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel29.setText("DOC. NOTE AND STAMP");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(43, 43, 43))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel29))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel29)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 310, 470));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jButton1.setText("DELETE");
        jButton1.setActionCommand("");

        jButton2.setText("DOCTOR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("PATIENT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("PRESCRIPTION");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("LOGIN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("RESET");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("PRINT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("EXIT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 910, 50));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 150, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel11.setText("PATEINT'S ADD.:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 130, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel12.setText("SIDE EFFECTS:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, -1, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel13.setText("ALLERGIC:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel14.setText("ISSUED DATE:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 30));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel15.setText("NO. OF TAB.:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, 30));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel16.setText("DOSAGE :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 30));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel17.setText("EXPIRY DATE:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, 30));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel18.setText("REF.NUM:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 30));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel19.setText("NAME OF TABLETS:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Acne", "AIDS/HIV", "Allergies", "Alzheimer's", "Arthritis", "Asthma", "Bipolar Disorder", "Cancer", "Cholesterol", "Colds & Flu", "Constipation", "COPD", "Covid 19", "Diabetes", "Gastro Center", "Hair Loss", "Menopause", "Smoking Cessation", "EMERGENCY", "OTHERS" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 120, 30));

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel20.setText("PATIENT'S DISEASE:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 30));

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel21.setText("FURTHER INFO:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 120, 30));

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel22.setText("DISCRIPTION:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 130, 30));

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel23.setText("HOW TO USE MED:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 140, 30));

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel24.setText("PATIENT ID:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 110, 30));

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel25.setText("GOV. APPR. ID :");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 130, 30));

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel26.setText("PH.NO :");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 60, 30));

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel27.setText("PATIENT'S NAME:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 140, 30));

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel28.setText("DATE OF BIRTH :");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 130, 30));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 150, 30));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 150, 30));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 150, 30));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 150, 30));

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 150, 30));
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 150, 30));
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 150, 30));
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 150, 30));
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 150, 30));
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 150, 30));
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 150, 30));
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 150, 30));
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 150, 30));
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 150, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Gabapentin (Neurontin).", "Hydrochlorothiazide (Esidrix, Hydrodiuril, Microzide, Oretic, Zide). ", "Hydrocodone/acetaminophen (Lortab, Norco, Vicodin, various others). ", "Sertraline (Zoloft).", "Furosemide (Lasix). ", "Fluticasone (Flonase, Flovent, Cutivate, various others). ", "Acetaminophen (Tylenol, various others).", "Amoxicillin (Amoxil, Polymox, Trimox, various others). ", "Alprazolam (Xanax).", "Atenolol (Tenormin).", "Citalopram (Celexa). ", "Insulin glargine (Lantus, Toujeo). ", "Montelukast (Singulair). ", "25,326,687", "Trazodone (Desyrel, various others). ", "Pantoprazole (Protonix). ", "Escitalopram (Lexapro). ", "Pravastatin (Pravachol). ", "Bupropion (Budeprion, Buproban, Wellbutrin, Zyban, various others). ", "Fluoxetine (Prozac, Rapiflux, Sarafem, Selfemra). ", "Carvedilol (Coreg).", "Prednisone (Deltasone, various others).", "Tamsulosin (Flomax). ", "Potassium (K-Dur, Klor-Con, Klotrix, Micro-K, Slow-K, various others). ", "Clopidogrel (Plavix). ", "Ibuprofen (Advil, Motrin, various others).", "Meloxicam (Mobic). ", "Rosuvastatin (Crestor). ", "Aspirin (various). ", "Tramadol (Ultram, various others).", "Zolpidem (Ambien, Intermezzo, various others).", "Warfarin (Coumadin). ", "Clonazepam (Klonopin). ", "Propranolol (Inderal, InnoPran, Pronol). ", "Glipizide (Glucotrol). ", "Dextroamphetamine/amphetamine salts (Adderall). ", "Cyclobenzaprine (Flexeril). ", "Methylphenidate (Concerta, Metadate, Ritalin, various others). ", "Duloxetine (Cymbalta). ", "Azithromycin (Zithromax). ", "Ranitidine (Zantac). ", "Lisinopril", "Metformin", "Atorvastatin", "Amlodipine", "Metoprolol", "Omeprazole", "Simvastatin", "Albuterol", "Losartan" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 120, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "HS", "TDS", "OD", "BD", "QID", "A/D", "WEEKLY" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 150, 30));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "          ID", "        NAME", "       DISEASE", " MEDICNIE", "  DOSAGE", "DISCRIPTION"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 590, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"SELECT"}));
        if(jComboBox3.getSelectedItem().equals("Acne")){
        jTextField20.setText("UK/HR/AL/32/43");
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "HS", "TDS", "OD", "BD", "QID", "A/D", "WEEKLY" }));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retinoids and retinoid-like drugs.", "clindamycin with benzoyl peroxide ", "(Benzaclin, Duac, Acanya) ", "erythromycin with benzoyl peroxide (Benzamycin)", " ", "azelaic acid (Azelex, Finacea)", " ", "Dapsone.", " ", "(Aldactone)", "Amnesteem", "Claravis", "Sotret" }));
        jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("STRESS AND FRICTION ON SKIN");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        else  if(jComboBox3.getSelectedItem().equals("AIDS/HIV")){
        jTextField20.setText("UK/HR/AL/32/43");
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "HS", "TDS", "OD", "BD", "QID", "A/D", "WEEKLY" }));
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retinoids and retinoid-like drugs.", "clindamycin with benzoyl peroxide ", "(Benzaclin, Duac, Acanya) ", "erythromycin with benzoyl peroxide (Benzamycin)", " ", "azelaic acid (Azelex, Finacea)", " ", "Dapsone.", " ", "(Aldactone)", "Amnesteem", "Claravis", "Sotret" }));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "abacavir / dolutegravir / lamivudine", "bictegravir / emtricitabine / tenofovir alafenamide fumarate", " ", "cobicistat / elvitegravir / emtricitabine / tenofovir alafenamide fumarate", "dolutegravir / lamivudine", "lamivudine / zidovudine" }));
        jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("headache" +"tiredness."+"diarrhea.respiratory tract infections");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        else if(jComboBox3.getSelectedItem().equals("Allergies")){
        jTextField20.setText("UK/HR/AL/32/43");
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "HS", "TDS", "OD", "BD", "QID", "A/D", "WEEKLY" }));
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retinoids and retinoid-like drugs.", "clindamycin with benzoyl peroxide ", "(Benzaclin, Duac, Acanya) ", "erythromycin with benzoyl peroxide (Benzamycin)", " ", "azelaic acid (Azelex, Finacea)", " ", "Dapsone.", " ", "(Aldactone)", "Amnesteem", "Claravis", "Sotret" }));
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "abacavir / dolutegravir / lamivudine", "bictegravir / emtricitabine / tenofovir alafenamide fumarate", " ", "cobicistat / elvitegravir / emtricitabine / tenofovir alafenamide fumarate", "dolutegravir / lamivudine", "lamivudine / zidovudine" }));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aspirin, ampicillin", "Nasal corticosteroid sprays ", "Longer-acting (second generation) antihistamines ", "Shorter-acting (first generation) antihistamines ", "Decongestants ", "Cromolyn sodium ", "Leukotriene inhibitors " }));
        jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("respiratory tract infections");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        else if(jComboBox3.getSelectedItem().equals("Alzheimer's")){
        jTextField20.setText("UK/HR/AL/32/43");
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "HS", "TDS", "OD", "BD", "QID", "A/D", "WEEKLY" }));
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retinoids and retinoid-like drugs.", "clindamycin with benzoyl peroxide ", "(Benzaclin, Duac, Acanya) ", "erythromycin with benzoyl peroxide (Benzamycin)", " ", "azelaic acid (Azelex, Finacea)", " ", "Dapsone.", " ", "(Aldactone)", "Amnesteem", "Claravis", "Sotret" }));
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "abacavir / dolutegravir / lamivudine", "bictegravir / emtricitabine / tenofovir alafenamide fumarate", " ", "cobicistat / elvitegravir / emtricitabine / tenofovir alafenamide fumarate", "dolutegravir / lamivudine", "lamivudine / zidovudine" }));
       // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aspirin, ampicillin", "Nasal corticosteroid sprays ", "Longer-acting (second generation) antihistamines ", "Shorter-acting (first generation) antihistamines ", "Decongestants ", "Cromolyn sodium ", "Leukotriene inhibitors " }));
       jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aricept", "Namenda", "donepezil", "memantine", "Exelon", "Namenda XR", "galantamine", "rivastigmine", "ergoloid mesylates", "Vita-Plus E Natural", "Aquavite-E" })); 
       jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("DIFFICULT THINKING AND UNDERSTANDING");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        else if(jComboBox3.getSelectedItem().equals(" Anxiety")){
        jTextField20.setText("UK/HR/AL/32/43");
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "HS", "TDS", "OD", "BD", "QID", "A/D", "WEEKLY" }));
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retinoids and retinoid-like drugs.", "clindamycin with benzoyl peroxide ", "(Benzaclin, Duac, Acanya) ", "erythromycin with benzoyl peroxide (Benzamycin)", " ", "azelaic acid (Azelex, Finacea)", " ", "Dapsone.", " ", "(Aldactone)", "Amnesteem", "Claravis", "Sotret" }));
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "abacavir / dolutegravir / lamivudine", "bictegravir / emtricitabine / tenofovir alafenamide fumarate", " ", "cobicistat / elvitegravir / emtricitabine / tenofovir alafenamide fumarate", "dolutegravir / lamivudine", "lamivudine / zidovudine" }));
       // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aspirin, ampicillin", "Nasal corticosteroid sprays ", "Longer-acting (second generation) antihistamines ", "Shorter-acting (first generation) antihistamines ", "Decongestants ", "Cromolyn sodium ", "Leukotriene inhibitors " }));
       //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aricept", "Namenda", "donepezil", "memantine", "Exelon", "Namenda XR", "galantamine", "rivastigmine", "ergoloid mesylates", "Vita-Plus E Natural", "Aquavite-E" })); 
       jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5-hydroxytryptophan", "Gotu kola", "Kava", "Lavender", "L-tryptophan Valerian", "prochlorperazine", "doxepin", "atenolol", "paroxetine", "venlafaxine", "diazepam", "buspirone" }));
       jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("excessive, ongoing worry and tension.");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
        else if(jComboBox3.getSelectedItem().equals("Arthritis")){
        jTextField20.setText("UK/HR/AL/32/43");
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "HS", "TDS", "OD", "BD", "QID", "A/D", "WEEKLY" }));
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retinoids and retinoid-like drugs.", "clindamycin with benzoyl peroxide ", "(Benzaclin, Duac, Acanya) ", "erythromycin with benzoyl peroxide (Benzamycin)", " ", "azelaic acid (Azelex, Finacea)", " ", "Dapsone.", " ", "(Aldactone)", "Amnesteem", "Claravis", "Sotret" }));
        //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "abacavir / dolutegravir / lamivudine", "bictegravir / emtricitabine / tenofovir alafenamide fumarate", " ", "cobicistat / elvitegravir / emtricitabine / tenofovir alafenamide fumarate", "dolutegravir / lamivudine", "lamivudine / zidovudine" }));
       // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aspirin, ampicillin", "Nasal corticosteroid sprays ", "Longer-acting (second generation) antihistamines ", "Shorter-acting (first generation) antihistamines ", "Decongestants ", "Cromolyn sodium ", "Leukotriene inhibitors " }));
       //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aricept", "Namenda", "donepezil", "memantine", "Exelon", "Namenda XR", "galantamine", "rivastigmine", "ergoloid mesylates", "Vita-Plus E Natural", "Aquavite-E" })); 
       //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5-hydroxytryptophan", "Gotu kola", "Kava", "Lavender", "L-tryptophan Valerian", "prochlorperazine", "doxepin", "atenolol", "paroxetine", "venlafaxine", "diazepam", "buspirone" }));
       jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cimzia (certolizumab)", "Enbrel, Erelzi (etanercept)", "Humira, Amjevita (adalimumab)", "Remicade, Inflectra, Ixifi, Renflexis (infliximab)", "Simponi (golimumab)", "Disease Modifying Anti-Rheumatic Drugs (DMARDs)", "Tumor Necrosis Factor (TNF) alfa inhibitors", "TNF alfa inhibitors for rheumatoid arthritis", "Acetaminophen (Tylenol, others)", "NSAIDs (Non-steroidal anti-inflammatory drugs)", "COX-2 inhibitors", "Salicylates", "Topical pain relief agents", "Corticosteroids and intra-articular corticosteroid injections", "Non-prescription herbal and dietary supplements", "Artificial joint fluid " }));
       jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("PAIN AND STIFFNESS IN JOINTS");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
        else if(jComboBox3.getSelectedItem().equals("Asthma")){
        jTextField20.setText("UK/HR/AL/32/43");
        // "Humira, Amjevita (adalimumab)", "Remicade, Inflectra, Ixifi, Renflexis (infliximab)", "Simponi (golimumab)", "Disease Modifying Anti-Rheumatic Drugs (DMARDs)", "Tumor Necrosis Factor (TNF) alfa inhibitors", "TNF alfa inhibitors for rheumatoid arthritis", "Acetaminophen (Tylenol, others)", "NSAIDs (Non-steroidal anti-inflammatory drugs)", "COX-2 inhibitors", "Salicylates", "Topical pain relief agents", "Corticosteroids and intra-articular corticosteroid injections", "Non-prescription herbal and dietary supplements", "Artificial joint fluid " }));
      jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "montelukast", "Singulair", "Dulera", "prednisone", "Atrovent", "Breo Ellipta", "ipratropium", "Alvesco", "methylprednisolone", "Atrovent HFA", "Kenalog-40", "Depo-Medrol", "Solu-Medrol" })); 
      jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("DIFFICULT IN BREATHING AND CHEST PAIN");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        else if(jComboBox3.getSelectedItem().equals("Bipolar Disorder")){
        jTextField20.setText("UK/HR/AL/32/43");
      jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "amotrigine", "lithium", "quetiapine", "divalproex sodium", "risperidone", "aripiprazole", "olanzapine", "carbamazepine", "ziprasidone", "lurasidone", "fluoxetine / olanzapine", "asenapine", "cariprazine" }));
      jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("MOOD SWINGS , IRRITABILITY,STRESS AND AGRESSION");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
        else if(jComboBox3.getSelectedItem().equals("Cholesterol")){
        jTextField20.setText("UK/HR/AL/32/43");
      //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "amotrigine", "lithium", "quetiapine", "divalproex sodium", "risperidone", "aripiprazole", "olanzapine", "carbamazepine", "ziprasidone", "lurasidone", "fluoxetine / olanzapine", "asenapine", "cariprazine" }));
     // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "carboplatin", "Adriamycin", "fluorouracil", "doxorubicin", "etoposide", "cyclophosphamide", "Cosmegen", "chlorambucil", "VePesid", "fludarabine" }));
     jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Statins", "atorvastatin (Lipitor)", "fluvastatin (Lescol)", " rosuvastatin (Crestor).", "alirocumab (Praluent) ", "evolocumab (Repatha).", "Ezetimibe (Zetia)", "cholestyramine (Prevalite, Questran, Questran Light)", "colesevelam (Welchol).", "niacin (Niacor)", "ezetimibe and simvastatin (Vytorin)" })); 
     jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("DIARHEA , CONSTIPATI0N AND NAUSEA.");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
        else if(jComboBox3.getSelectedItem().equals("Colds & Flu")){
        jTextField20.setText("UK/HR/AL/32/43");
      //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "amotrigine", "lithium", "quetiapine", "divalproex sodium", "risperidone", "aripiprazole", "olanzapine", "carbamazepine", "ziprasidone", "lurasidone", "fluoxetine / olanzapine", "asenapine", "cariprazine" }));
      jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benadryl", "chlorpheniramine", "Coricidin HBP Cold & Flu", "Vicks Nyquil D Cold and Flu Nighttime Relief", "diphenhydramine", "Coricidin HBP Maximum Strength Flu", "Diphedryl", "Aprodine", "Dytuss", "Valu-Dryl", "acetaminophen / dextromethorphan / guaifenesin / phenylephrine" }));
      jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("DRY MOUTH , UPSET STOMACH , MILD HEADACHE");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
        
         else if(jComboBox3.getSelectedItem().equals("Constipation")){
        jTextField20.setText("UK/HR/AL/32/43");
      //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "amotrigine", "lithium", "quetiapine", "divalproex sodium", "risperidone", "aripiprazole", "olanzapine", "carbamazepine", "ziprasidone", "lurasidone", "fluoxetine / olanzapine", "asenapine", "cariprazine" }));
     // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "carboplatin", "Adriamycin", "fluorouracil", "doxorubicin", "etoposide", "cyclophosphamide", "Cosmegen", "chlorambucil", "VePesid", "fludarabine" }));
     //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Statins", "atorvastatin (Lipitor)", "fluvastatin (Lescol)", " rosuvastatin (Crestor).", "alirocumab (Praluent) ", "evolocumab (Repatha).", "Ezetimibe (Zetia)", "cholestyramine (Prevalite, Questran, Questran Light)", "colesevelam (Welchol).", "niacin (Niacor)", "ezetimibe and simvastatin (Vytorin)" })); 
     jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "docusate", "Metamucil", "bisacodyl", "Linzess", "Dulcolax Stool Softener", "polyethylene glycol 3350", "Doc-Q-Lace", "psyllium", "Enemeez Mini" }));
     jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("ABDOMINAL DISCOMFORT,BLOATING,SENSE OF INCOMPLETE EVACUATION");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
        else if(jComboBox3.getSelectedItem().equals("COPD")){
        jTextField20.setText("UK/HR/AL/32/43");
      // (Lescol)", " rosuvastatin (Crestor).", "alirocumab (Praluent) ", "evolocumab (Repatha).", "Ezetimibe (Zetia)", "cholestyramine (Prevalite, Questran, Questran Light)", "colesevelam (Welchol).", "niacin (Niacor)", "ezetimibe and simvastatin (Vytorin)" })); 
    // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "docusate", "Metamucil", "bisacodyl", "Linzess", "Dulcolax Stool Softener", "polyethylene glycol 3350", "Doc-Q-Lace", "psyllium", "Enemeez Mini" }));
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "budesonide / formoterol", "Daliresp", "prednisone", "Stiolto Respimat", "budesonide / formoterol", "aclidinium", "Incruse Ellipta", "umeclidinium", "olodaterol" })); 
    jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("CHRONIC COUGH ,WHEEZING AND SHORTNESS OF BREATHE");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
        else if(jComboBox3.getSelectedItem().equals("Covid 19")){
        jTextField20.setText("UK/HR/AL/32/43");
      // (Lescol)", " rosuvastatin (Crestor).", "alirocumab (Praluent) ", "evolocumab (Repatha).", "Ezetimibe (Zetia)", "cholestyramine (Prevalite, Questran, Questran Light)", "colesevelam (Welchol).", "niacin (Niacor)", "ezetimibe and simvastatin (Vytorin)" })); 
    // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "docusate", "Metamucil", "bisacodyl", "Linzess", "Dulcolax Stool Softener", "polyethylene glycol 3350", "Doc-Q-Lace", "psyllium", "Enemeez Mini" }));
    //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "budesonide / formoterol", "Daliresp", "prednisone", "Stiolto Respimat", "budesonide / formoterol", "aclidinium", "Incruse Ellipta", "umeclidinium", "olodaterol" })); 
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hydroxychloroquine", "chloroquine" }));
    jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("FEVER , TIREDNESS AND DRY COUGH");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
        else if(jComboBox3.getSelectedItem().equals("Diabetes")){
        jTextField20.setText("UK/HR/AL/32/43");
      // (Lescol)", " rosuvastatin (Crestor).", "alirocumab (Praluent) ", "evolocumab (Repatha).", "Ezetimibe (Zetia)", "cholestyramine (Prevalite, Questran, Questran Light)", "colesevelam (Welchol).", "niacin (Niacor)", "ezetimibe and simvastatin (Vytorin)" })); 
    // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "docusate", "Metamucil", "bisacodyl", "Linzess", "Dulcolax Stool Softener", "polyethylene glycol 3350", "Doc-Q-Lace", "psyllium", "Enemeez Mini" }));
    //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "budesonide / formoterol", "Daliresp", "prednisone", "Stiolto Respimat", "budesonide / formoterol", "aclidinium", "Incruse Ellipta", "umeclidinium", "olodaterol" })); 
    //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hydroxychloroquine", "chloroquine" }));
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ketoacidosis", "Basaglar (insulin glargine)", "Admelog (insulin lispro)", "Afrezza", "glimepiride and pioglitazone", "glyburide and metformin", "glipizide and metformin" }));
    jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("EXCESSIVE THRUST OR URINATION,BLURRED VISION , WEIGHT LOSS");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
        else if(jComboBox3.getSelectedItem().equals("Gastro Center")){
        jTextField20.setText("UK/HR/AL/32/43");
    //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ketoacidosis", "Basaglar (insulin glargine)", "Admelog (insulin lispro)", "Afrezza", "glimepiride and pioglitazone", "glyburide and metformin", "glipizide and metformin" }));
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gaviscon", "Maalox", "Milk of Magnesia", "Mylanta", "Rolaids", "Tums", "Histamine-2 (H2) Antagonists", "Proton Pump Inhibitors (PPIs)" }));
    jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("EXCESSIVE THRUST OR URINATION,BLURRED VISION , WEIGHT LOSS");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        else if(jComboBox3.getSelectedItem().equals("Hair Loss")){
        jTextField20.setText("UK/HR/AL/32/43");
    //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ketoacidosis", "Basaglar (insulin glargine)", "Admelog (insulin lispro)", "Afrezza", "glimepiride and pioglitazone", "glyburide and metformin", "glipizide and metformin" }));
    //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gaviscon", "Maalox", "Milk of Magnesia", "Mylanta", "Rolaids", "Tums", "Histamine-2 (H2) Antagonists", "Proton Pump Inhibitors (PPIs)" }));
    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propecia (finasteride)", "Rogaine (for Men and Women)", "Avacor, Good Sense, Rogaine Extra Strength (for Men)" }));
    jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("HAIR LOSS ON TOP AND FRONT PORTION OF HEAD");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        else if(jComboBox3.getSelectedItem().equals("Menopause")){
        jTextField20.setText("UK/HR/AL/32/43");
   // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propecia (finasteride)", "Rogaine (for Men and Women)", "Avacor, Good Sense, Rogaine Extra Strength (for Men)" }));
   jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "estradiol (17B-estradiol)", "esterified estrogens", "ospemifene", "prasterone*" })); 
   jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("breast tenderness" +"nausea" +"bloating" +"leg cramps");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
        else if(jComboBox3.getSelectedItem().equals("Smoking Cessation")){
        jTextField20.setText("UK/HR/AL/32/43");
   // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propecia (finasteride)", "Rogaine (for Men and Women)", "Avacor, Good Sense, Rogaine Extra Strength (for Men)" }));
  // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "estradiol (17B-estradiol)", "esterified estrogens", "ospemifene", "prasterone*" })); 
  jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chantix (varenicline)", "Zyban (bupropion sustained release [SR])", "Chantix (varenicline)" })); 
  jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("CANCER, HEARING FAILURE , LUNGS FAILURE");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        else if(jComboBox3.getSelectedItem().equals("EMERGENCY")||jComboBox3.getSelectedItem().equals("OTHERS")){
        jTextField20.setText("UK/HR/AL/32/43");
   // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propecia (finasteride)", "Rogaine (for Men and Women)", "Avacor, Good Sense, Rogaine Extra Strength (for Men)" }));
  // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "estradiol (17B-estradiol)", "esterified estrogens", "ospemifene", "prasterone*" })); 
  //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chantix (varenicline)", "Zyban (bupropion sustained release [SR])", "Chantix (varenicline)" })); 
  jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gabapentin (Neurontin).", "Hydrochlorothiazide (Esidrix, Hydrodiuril, Microzide, Oretic, Zide). ", "Hydrocodone/acetaminophen (Lortab, Norco, Vicodin, various others). ", "Sertraline (Zoloft).", "Furosemide (Lasix). ", "Fluticasone (Flonase, Flovent, Cutivate, various others). ", "Acetaminophen (Tylenol, various others).", "Amoxicillin (Amoxil, Polymox, Trimox, various others). ", "Alprazolam (Xanax).", "Atenolol (Tenormin).", "Citalopram (Celexa). ", "Insulin glargine (Lantus, Toujeo). ", "Montelukast (Singulair). ", "25,326,687", "Trazodone (Desyrel, various others). ", "Pantoprazole (Protonix). ", "Escitalopram (Lexapro). ", "Pravastatin (Pravachol). ", "Bupropion (Budeprion, Buproban, Wellbutrin, Zyban, various others). ", "Fluoxetine (Prozac, Rapiflux, Sarafem, Selfemra). ", "Carvedilol (Coreg).", "Prednisone (Deltasone, various others).", "Tamsulosin (Flomax). ", "Potassium (K-Dur, Klor-Con, Klotrix, Micro-K, Slow-K, various others). ", "Clopidogrel (Plavix). ", "Ibuprofen (Advil, Motrin, various others).", "Meloxicam (Mobic). ", "Rosuvastatin (Crestor). ", "Aspirin (various). ", "Tramadol (Ultram, various others).", "Zolpidem (Ambien, Intermezzo, various others).", "Warfarin (Coumadin). ", "Clonazepam (Klonopin). ", "Propranolol (Inderal, InnoPran, Pronol). ", "Glipizide (Glucotrol). ", "Dextroamphetamine/amphetamine salts (Adderall). ", "Cyclobenzaprine (Flexeril). ", "Methylphenidate (Concerta, Metadate, Ritalin, various others). ", "Duloxetine (Cymbalta). ", "Azithromycin (Zithromax). ", "Ranitidine (Zantac). ", "Lisinopril", "Metformin", "Atorvastatin", "Amlodipine", "Metoprolol", "Omeprazole", "Simvastatin", "Albuterol", "Losartan" }));
  jTextField22.setText("07/02/2020");
        jTextField23.setText("07/02/2022");
        jTextField21.setText("10");
        jTextField10.setText("CANCER, HEARING FAILURE , LUNGS FAILURE");
        jTextField12.setText("USE WATER NO ALCOHOL");
        }
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       
        String url="jdbc:mysql://localhost:3306/hospital";
        String query="select id,name,disease,medicine,dosage,discripton from prescription;";
             String username1="root";
        String pass="";
        Connection conn=null;
        String a=null;
        String b=null;
        Statement s=null;
            try{
                Class.forName("com.mysql.jdbc.Driver");
        conn=DriverManager.getConnection(url,username1,pass);
        System.out.println("Connected");
        s=     (Statement) conn.createStatement();
        ResultSet rs=s.executeQuery(query);
        //System.out.println(rs);
        while(rs.next()){
                 int id=rs.getInt(1);
                 String id1=Integer.toString(id);
        String name=rs.getString(2);
        String disease=rs.getString(3);
        String medicine=rs.getString(4);
        String dosage=rs.getString(5);
        String discription=rs.getString(6);
        model.addRow(new Object[]{id1,name,disease,medicine,dosage,discription});
        }
        conn.close();
        
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);
            }
        
        String qty1=(String) (jComboBox3.getSelectedItem());
            String qty2 = (String)(jComboBox1.getSelectedItem());
            String qt3=(jTextField20.getText());
            String qty4 = (String)(jComboBox2.getSelectedItem());
            String qty5 = (String)(jComboBox4.getSelectedItem());
             String qt6=(jTextField21.getText());
              String qt7=(jTextField22.getText());
               String qt8=(jTextField23.getText());
                String qt9=(jTextField10.getText());
                 String qt10=(jTextField18.getText());
                  String qt11=(jTextField11.getText());
             String qt12=(jTextField12.getText());
              String qt13=(jTextField13.getText());
               String qt14=(jTextField14.getText());
                String qt15=(jTextField15.getText());
                 String qt16=(jTextField16.getText());
                  String qt17=(jTextField17.getText());
                   String qt18=(jTextField9.getText());
                   
                   //14 is id:
                   
                   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            // TODO add your handling code here:
            frame = new JFrame();
            if(JOptionPane.showConfirmDialog(frame,"CONFIRM IF YOU WANT TO EXIT!","AGARWAL MEDICAL CENTER",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
            }
            
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
        jTextArea1.print();
        
        }catch(PrinterException ex){
       // Logger.getLogger(hospital.class.getName()).log(level.SEVERE,null,ex);
        Logger.getLogger(hospital.class.getName()).log(null , null, ex);
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        // jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"SELECT"}));
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            // TODO add your handling code here:
             String url="jdbc:mysql://localhost:3306/hospital";
        String query="SELECT id,name,dob,address,govid,phno FROM prescription ORDER BY ID Desc Limit 1";
             String username1="root";
        String pass="";
        Connection conn=null;
        String a=null;
        String b=null;
        Statement s=null;
            try{
                Class.forName("com.mysql.jdbc.Driver");
        conn=DriverManager.getConnection(url,username1,pass);
        System.out.println("Connected");
        s=     (Statement) conn.createStatement();
        ResultSet rs=s.executeQuery(query);
        //System.out.println(rs);
        if(rs.next()){
                 int id=rs.getInt(1);
                 String id1=Integer.toString(id);
        String name=rs.getString(2);
        String dob=rs.getString(3);
        String address=rs.getString(4);
        String govid=rs.getString(5);
        String phno=rs.getString(6);
       // jTextField13.setText(id1);
        //jTextField16.setText(name);
        //jTextField17.setText(dob);
        //jTextField14.setText(govid);
        //jTextField9.setText(address);
        //jTextField15.setText(phno);
        }
        conn.close();
        
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);
            }
           
            String qty1=(String) (jComboBox3.getSelectedItem());
            String qty2 = (String)(jComboBox1.getSelectedItem());
            String qt3=(jTextField20.getText());
            String qty4 = (String)(jComboBox2.getSelectedItem());
            String qty5 = (String)(jComboBox4.getSelectedItem());
             String qt6=(jTextField21.getText());
              String qt7=(jTextField22.getText());
               String qt8=(jTextField23.getText());
                String qt9=(jTextField10.getText());
                 String qt10=(jTextField18.getText());
                  String qt11=(jTextField11.getText());
             String qt12=(jTextField12.getText());
              String qt13=(jTextField13.getText());
               String qt14=(jTextField14.getText());
                String qt15=(jTextField15.getText());
                 String qt16=(jTextField16.getText());
                  String qt17=(jTextField17.getText());
                   String qt18=(jTextField9.getText());
                   
                   
                   jTextArea1.setText("");
                   jTextArea1.append("PATIENT ID: "+qt13+"\n------------------------------------\n"+"\nREFERNCE NUMBER : "+qt3+"\n------------------------------------\n"+"\nPATIENT NAME : "+qt16+"\n------------------------------------\n"+"\nDATE OF BIRTH : "+qt17+"\n------------------------------------\n"+"\nPATIENT'S ADDRESS : "+qt18+"\n------------------------------------\n"+"\nPATIENT'S NUMBER : "+qt15+"\n------------------------------------\n"+"\nDISEASE : "+qty1+"\n------------------------------------\n"+"\nALLERGIC : "+qty2+"\n------------------------------------\n"+"\nNAME OF TABLET : "+qty4+"\n------------------------------------\n"+"\nDOSAGE :"+qty5+"\n------------------------------------\n"+"\nNUMBER OF TABLETS :"+qt6+"\n------------------------------------\n"+"\nSIDE EFFECTS : "+qt9+"\n------------------------------------\n"+"\nEXPIRY DATE : "+qt8);
            
        //database connectivity:::
       // String sql="insert into prescription(id,name,dob,address,phno,disease,medicine,dosage,tablets,discripton,govid) values("+qt13+","+qt16+","+qt17+","+qt18+","+qt15+","+qty1+","+qty4+","+qty5+","+qt6+","+qt11+","+qt14+"";
             url="jdbc:mysql://localhost:3306/hospital";
        username1="root";
         pass="";
        conn=null;
         a=null;
        b=null;
        PreparedStatement st=null;
        try{
        Class.forName("com.mysql.jdbc.Driver");
        conn=DriverManager.getConnection(url,username1,pass);
        System.out.println("Connected");
        //st=  (PreparedStatement) conn.prepareStatement(sql);
        st=  (PreparedStatement) conn.prepareStatement("insert into prescription(id,name,dob,address,disease,medicine,dosage,tablets,discripton,govid,phno) values(?,?,?,?,?,?,?,?,?,?,?)");  
        st.setString(1, qt13);
        st.setString(2, qt16);
        st.setString(3, qt17);
        st.setString(4, qt18);
      //  st.setString(5, qt15);
        st.setString(5, qty1);
        st.setString(6, qty4);
        st.setString(7, qty5);
        st.setString(8, qt6);
        st.setString(9, qt11);
        st.setString(10, qt14);
        st.setString(11, qt15);
        
        st.executeUpdate();
               //rst.next();
              //a= rst.getString("username");
              //b=rst.getString("password");
           // System.out.print("TABLE CREATED");
            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
           // return null;
        }
                   
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            // TODO add your handling code here:
            //initComponents();
           // jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT"}));
            jComboBox3.getModel().setSelectedItem("SELECT");
            //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT"}));
           // jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT"}));
            jTextField20.setText("");
             jTextField10.setText("");
              jTextField21.setText("");
               jTextField22.setText("");
                jTextField23.setText("");
                 jTextField12.setText("");
                  jTextArea1.setText("");
                 String url="jdbc:mysql://localhost:3306/hospital";
        String query="SELECT id,name,dob,address,govid,phno FROM prescription ORDER BY ID Desc Limit 1";
             String username1="root";
        String pass="";
        Connection conn=null;
        String a=null;
        String b=null;
        Statement s=null;
            try{
                Class.forName("com.mysql.jdbc.Driver");
        conn=DriverManager.getConnection(url,username1,pass);
        System.out.println("Connected");
        s=     (Statement) conn.createStatement();
        ResultSet rs=s.executeQuery(query);
        //System.out.println(rs);
        if(rs.next()){
                 int id=rs.getInt(1);
                 String id1=Integer.toString(id);
        String name=rs.getString(2);
        String dob=rs.getString(3);
        String address=rs.getString(4);
        String govid=rs.getString(5);
        String phno=rs.getString(6);
        jTextField13.setText(id1);
        jTextField16.setText(name);
        jTextField17.setText(dob);
        jTextField14.setText(govid);
        jTextField9.setText(address);
        jTextField15.setText(phno);
        }
        conn.close();
        
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);
            }
 
            
            
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
            login ih = new login();
            ih.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        doctor ih=new doctor();
        ih.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        patient_info ih=new patient_info();
        ih.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
 //public JPanelBackgroundColorTest() {
     // setTitle("JPanelBackgroundColor Test");
      
      //jPanel1.add(new JLabel("Welcome to Tutorials Point"));
      
   //}
}
